/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rohan
 */
public class third extends javax.swing.JFrame {
    
    String path;
    String emsg;
    BufferedImage sourceImage;
    BufferedImage img;
    /**
     * Creates new form third
     */
    public third() {
        initComponents();
    }
    public third(String msg) {
        initComponents();
        
        FileInputStream fis1 = null;
        
        try {
            File f1 = new File("path.txt");
            fis1 = new FileInputStream(f1);
            
            int content;
            while ((content = fis1.read()) != -1) {
                path+=(char)content;
            }
            path = path.substring(4);
            System.out.println(path);
            
            File f3 = new File(path);
            System.out.println(f3);
            sourceImage = ImageIO.read(f3);
            imgBox.setIcon(new ImageIcon(sourceImage));
            
            emsg=msg;
            encMsg.setText(emsg);
            fis1.close();
            
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgBox = new javax.swing.JLabel();
        encMsg = new javax.swing.JLabel();
        embedBtn = new javax.swing.JButton();
        embImg = new javax.swing.JLabel();
        savnxt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Embed Data and Image");

        embedBtn.setText("Embed");
        embedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                embedBtnActionPerformed(evt);
            }
        });

        savnxt.setText("Save & Next");
        savnxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savnxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Embedding In Image");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(embedBtn))
                    .addComponent(encMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(embImg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(savnxt)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(imgBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(encMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(embedBtn)
                .addGap(270, 270, 270))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(embImg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(savnxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void embedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_embedBtnActionPerformed
        String mess = emsg;
        //BufferedImage img = sourceImage;
        
        img = sourceImage.getSubimage(0,0,sourceImage.getWidth(),sourceImage.getHeight());
        
        int messageLength = mess.length(); 
        int imageWidth = img.getWidth(), imageHeight = img.getHeight(),imageSize = imageWidth * imageHeight;
        if(messageLength * 8 + 32 > imageSize) 
        {
            JOptionPane.showMessageDialog(this, "Message is too long for the chosen image","Message too long!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        embedInteger(img, messageLength, 0, 0);
        byte b[] = mess.getBytes();
        
        for(int i=0; i<b.length; i++)
            embedByte(img, b[i], i*8+32, 0);
        
        embImg.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_embedBtnActionPerformed

    private void embedInteger(BufferedImage img, int n, int start, int storageBit) 
    {
        int maxX = img.getWidth(), maxY = img.getHeight(), 
        startX = start/maxY, startY = start - startX*maxY, count=0;
        for(int i=startX; i<maxX && count<32; i++) 
        {
            for(int j=startY; j<maxY && count<32; j++) 
            {
                int rgb = img.getRGB(i, j), bit = getBitValue(n, count);
                rgb = setBitValue(rgb, storageBit, bit);
                img.setRGB(i, j, rgb);
                count++;
          }
       }
    }
    private void embedByte(BufferedImage img, byte b, int start, int storageBit) 
    {
        int maxX = img.getWidth(), maxY = img.getHeight(), 
        startX = start/maxY, startY = start - startX*maxY, count=0;
        for(int i=startX; i<maxX && count<8; i++) 
        {
            for(int j=startY; j<maxY && count<8; j++) 
            {
                int rgb = img.getRGB(i, j), bit = getBitValue(b, count);
                rgb = setBitValue(rgb, storageBit, bit);
                img.setRGB(i, j, rgb);
                count++;
            }
        }
    }
    
    private int getBitValue(int n, int location) 
    {
        int v = n & (int) Math.round(Math.pow(2, location));
        return v==0?0:1;
    }
    
    private int setBitValue(int n, int location, int bit) 
    {
        int toggle = (int) Math.pow(2, location), bv = getBitValue(n, location);
        
        if(bv == bit)
        return n;
        
        if(bv == 0 && bit == 1)
            n |= toggle;
        else if(bv == 1 && bit == 0)
            n ^= toggle;
        
        return n;
    }
    
    private void savnxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savnxtActionPerformed
        if(img == null) 
        {
            JOptionPane.showMessageDialog(this, "No message has been embedded!","Nothing to save", JOptionPane.ERROR_MESSAGE);
            return;
        }
        File f = new File("embed.png");
        try 
        {    
            if(f.exists()) 
            f.delete();
            ImageIO.write(img,"png", f);  
        } 
        catch(Exception ex)
        { 
            ex.printStackTrace();
        }
        
        new fourth().setVisible(true);
    }//GEN-LAST:event_savnxtActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(third.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(third.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(third.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(third.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new third().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel embImg;
    private javax.swing.JButton embedBtn;
    private javax.swing.JLabel encMsg;
    private javax.swing.JLabel imgBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton savnxt;
    // End of variables declaration//GEN-END:variables
}
